name: CI - Docker Requirements Check

on:
  push:
    branches: 
      - "main" 
      - "feat/**"
      - "fix/**"

jobs:
  docker-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          cat <<EOF > .env
          AIRFLOW_IMAGE_NAME=${{ secrets.AIRFLOW_IMAGE_NAME }}

          AIRFLOW__CORE__EXECUTOR=${{ secrets.AIRFLOW__CORE__EXECUTOR }}
          AIRFLOW__CORE__FERNET_KEY=${{ secrets.AIRFLOW__CORE__FERNET_KEY }}
          AIRFLOW__CORE__LOAD_EXAMPLES=${{ secrets.AIRFLOW__CORE__LOAD_EXAMPLES }}
          AIRFLOW_UID=${{ secrets.AIRFLOW_UID }}

          AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=${{ secrets.AIRFLOW__DATABASE__SQL_ALCHEMY_CONN }}

          AIRFLOW_POSTGRES_USER=${{ secrets.AIRFLOW_POSTGRES_USER }}
          AIRFLOW_POSTGRES_PASSWORD=${{ secrets.AIRFLOW_POSTGRES_PASSWORD }}
          AIRFLOW_POSTGRES_DB=${{ secrets.AIRFLOW_POSTGRES_DB }}
          
          MONGO_URI=${{ secrets.MONGO_URI }}
          MONGO_DB_NAME=${{ secrets.MONGO_DB_NAME }}
          MONGO_COLLECTION=${{ secrets.MONGO_COLLECTION }}

          API_URL=${{ secrets.API_URL }}
          EOF

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Start airflow-init container
        run: docker compose up -d airflow-init

      - name: Give access to folders
        run: |
          sudo chown -R $USER:$USER ./airflow/dags
          sudo chown -R $USER:$USER ./airflow/logs
          sudo chown -R $USER:$USER ./airflow/plugins
          sudo chown -R $USER:$USER ./src
          sudo chown -R $USER:$USER ./monitoring

      - name: Start containers
        run: docker compose up -d

      - name: Verify Airflow Initialization
        run: |
          CONTAINER_ID=$(docker compose ps -q airflow-init)
          EXIT_CODE=$(docker wait $CONTAINER_ID)
          if [ "$EXIT_CODE" != "0" ]; then
            echo "Airflow initialization failed"
            docker compose logs airflow-init
            exit 1
          fi

      - name: Check if any containers failed to start
        run: |
          BAD=$(docker compose ps --status created --status restarting -q)

          if [ -n "$BAD" ]; then
            echo "Some containers failed to start"
            docker compose ps -a
            exit 1
          fi

          echo "All containers started successfully"


      - name: Shutdown containers
        if: always()
        run: docker compose down -v
