name: CI - Docker Requirements Check

on:
  push:
    branches: 
      - "main" 
      - "feat/**"
      - "fix/**"

jobs:
  docker-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          cat <<EOF > .env
          AIRFLOW_IMAGE_NAME=${{ secrets.AIRFLOW_IMAGE_NAME }}

          AIRFLOW__CORE__EXECUTOR=${{ secrets.AIRFLOW__CORE__EXECUTOR }}
          AIRFLOW__CORE__FERNET_KEY=${{ secrets.AIRFLOW__CORE__FERNET_KEY }}
          AIRFLOW__CORE__LOAD_EXAMPLES=${{ secrets.AIRFLOW__CORE__LOAD_EXAMPLES }}
          AIRFLOW_UID=${{ secrets.AIRFLOW_UID }}

          AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=${{ secrets.AIRFLOW__DATABASE__SQL_ALCHEMY_CONN }}

          AIRFLOW_POSTGRES_USER=${{ secrets.AIRFLOW_POSTGRES_USER }}
          AIRFLOW_POSTGRES_PASSWORD=${{ secrets.AIRFLOW_POSTGRES_PASSWORD }}
          AIRFLOW_POSTGRES_DB=${{ secrets.AIRFLOW_POSTGRES_DB }}
          
          MONGO_URI=${{ secrets.MONGO_URI }}
          MONGO_DB_NAME=${{ secrets.MONGO_DB_NAME }}
          MONGO_COLLECTION=${{ secrets.MONGO_COLLECTION }}

          API_URL=${{ secrets.API_URL }}
          EOF

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Create folders for Airflow
        run: |
          mkdir -p airflow/dags
          mkdir -p airflow/logs
          mkdir -p airflow/plugins
          
      - name: Fix Airflow folder permissions
        run: |
          sudo chown -R ${{ secrets.AIRFLOW_UID }}:0 airflow
          sudo chmod -R 775 airflow

      - name: Start airflow-init container
        run: docker compose run --rm airflow-init

      - name: Start containers
        run: docker compose up -d

      - name: Wait for Airflow webserver
        run: sleep 70

      - name: Verify Python requirements in Airflow Webserver
        run: |
          CONTAINER_ID=$(docker compose ps -q airflow-webserver)

          echo "Checking Python packages in container $CONTAINER_ID"
          docker ps -a
          
          docker compose exec airflow-webserver pip show requests beautifulsoup4 supabase python-dotenv pymongo

      - name: Check if any containers failed to start
        run: |
          BAD=$(docker compose ps --status created --status restarting -q)

          if [ -n "$BAD" ]; then
            echo "Some containers failed to start"
            docker compose ps -a
            exit 1
          fi

          echo "All containers started successfully"


      - name: Shutdown containers
        if: always()
        run: docker compose down -v
